server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Service-Origin, Gateway
        - AddResponseHeader=X-Gateway, MetzNumericBank
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
              
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/account/**
              
        - id: client-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/client/**
              
        - id: bank-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/bank/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client.HttpClient: DEBUG